<a href="https://colab.research.google.com/github/Sai-Prathik/Neural-Networks/blob/main/Sample_training.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [ ]:
data=pd.read_csv("/content/drive/MyDrive/ML Pandas Assignment/Datasets/Advertising.csv")
data.drop("Unnamed: 0",inplace=True,axis=1)
data

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [ ]:
data_x=data[["TV","radio","newspaper"]]
data_y=data["sales"]

In [ ]:
def minmaxscaler(data,range):
  scaler=MinMaxScaler(feature_range=range)
  scaler.fit(data)
  return scaler.transform(data)

In [ ]:
data_x=np.array(minmaxscaler(data_x,(-1,1)))
data_x

array([[ 0.55157254,  0.52419355,  0.2119613 ],
       [-0.7037538 ,  0.58467742, -0.2119613 ],
       [-0.88840041,  0.85080645,  0.21372032],
       [ 0.01995265,  0.66532258,  0.0237467 ],
       [ 0.21812648, -0.56451613,  0.02198769],
       [-0.94589111,  0.97177419,  0.31398417],
       [-0.61582685,  0.32258065, -0.59190853],
       [-0.19174839, -0.20967742, -0.80123131],
       [-0.94656747, -0.91532258, -0.9876869 ],
       [ 0.3466351 , -0.89516129, -0.63236588],
       [-0.55765979, -0.76612903, -0.57959543],
       [ 0.44741292, -0.03225806, -0.93491645],
       [-0.84376057,  0.41532258,  0.15391381],
       [-0.34528238, -0.69354839, -0.87862797],
       [ 0.37571863,  0.3266129 , -0.19613017],
       [ 0.31687521,  0.9233871 , -0.07475814],
       [-0.54616165,  0.47580645,  1.        ],
       [ 0.89854582,  0.59677419, -0.0237467 ],
       [-0.53669259, -0.1733871 , -0.68337731],
       [-0.00845451, -0.03629032, -0.66930519],
       [ 0.47243828,  0.11693548, -0.065

In [ ]:
data_y=np.array((data_y-data_y.min())/(data_y.max()-data_y.min()))

In [ ]:
type(data_y)

numpy.ndarray

In [ ]:
data_y=data_y.reshape(-1,1)

In [ ]:
def init_weights(n,k):
  l=[]
  for i in range(k):
   l.append(np.random.uniform(-1,1,n))
  return np.array(l)
  

In [ ]:
class FeedForward:
  def __init__(self,n_inputs,n_neurons,lr_rate):
    self.w1=init_weights(n_inputs,n_neurons)
    self.w2=init_weights(1,n_neurons)
    self.b1=init_weights(1,n_neurons)
    self.b2=init_weights(1,1)
    self.lr_rate=lr_rate
    self.h1=None
    self.h2=None
  
  def sigmoid(self,X):
     
    return 1/(1+np.exp(-X))

  def calc(self,X):
     
    self.h1=self.sigmoid(np.dot(self.w1,X).reshape(-1,1)+self.b1)
    self.h2=np.dot(self.h1.T,self.w2)+self.b2
     
    return self.h2

  def fit(self,X,y):
    l=[]
    #for i,j in zip(X,y):
       
    e=self.calc(X)-y
      
    while e[0][0]>0.01 :
       
      backtrack_error(self,X,e)
      e=self.calc(X)-y
     
     
   # l.append(self.calc(i))
    #return np.array(l)

       
       
        
     
      

In [ ]:
np.random.seed(1)
model=FeedForward(3,3,0.1)
#model.fit(data_x,data_y)
print(model.fit(data_x[2],data_y[2]),data_y[2])
 

(1, 3)
(1, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
(3, 3)
None [0.30314961]


In [ ]:
def get_diagonal_vec(n,x):#diagonal vector
  #print("get_digonal_vec")
  a=np.zeros((n,n),float)
  np.fill_diagonal(a,x)
  return a

In [ ]:
def get_multiples(model): #v(z(1-z))
  #print("get_multiples")
  x1=np.dot(get_diagonal_vec(3,model.h1),(1-model.h1))
  y1=np.dot(get_diagonal_vec(3,model.w2),x1)
  return y1

In [ ]:
def backtrack_error(model,X,e):
    #print("backtrack_error")
    cm=get_multiples(model)
     
    bias_vec=cm #biases(3X1)
    l=[]
    for i in cm.T:
      l.append(i*X[0])
     
    hidden_weights=np.array(l)#hidden weights(3X3)
     
    output_weights=model.h1.T #output weights(3X1)
    
  
    print(output_weights.shape)
    model.w1=model.w1-(model.lr_rate*(hidden_weights*e))
    model.w2=model.w2-(model.lr_rate*(output_weights*e))
    model.b1=model.b1-(model.lr_rate*(bias_vec*e))
    model.b2=model.b2-(model.lr_rate*e)
     
     

In [ ]:
a=np.array([1,2,3])
backtrack_error(model,a,1.5)


[[0.83256057 0.77803821 0.86983433]
 [0.97786541 0.79765271 0.45922058]
 [0.7801008  0.11741767 0.63863589]]


In [ ]:
model.w1

array([[0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936],
       [0.78052918, 0.11827443, 0.63992102]])